"""study and bookings

Revision ID: f4cca8633cf6
Revises: 96c7585d7570
Create Date: 2023-08-01 00:26:41.732679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4cca8633cf6'
down_revision = '96c7585d7570'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.drop_column('bookings', 'end')
    op.drop_column('bookings', 'start')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'end_time')
    op.drop_column('bookings', 'start_time')
    # ### end Alembic commands ###
